#include "trimesh.h"
#include <algorithm>
#include <assert.h>
#include <cmath>
#include <float.h>
#include <string.h>
#include "../ui/TraceUI.h"
extern TraceUI *traceUI;
extern TraceUI *traceUI;

using namespace std;

Trimesh::~Trimesh() {
  for (auto f : faces)
    delete f;
}

// must add vertices, normals, and materials IN ORDER
void Trimesh::addVertex(const glm::dvec3 &v) { vertices.emplace_back(v); }

void Trimesh::addNormal(const glm::dvec3 &n) { normals.emplace_back(n); }

void Trimesh::addColor(const glm::dvec3 &c) { vertColors.emplace_back(c); }

void Trimesh::addUV(const glm::dvec2 &uv) { uvCoords.emplace_back(uv); }

// Returns false if the vertices a,b,c don't all exist
bool Trimesh::addFace(int a, int b, int c) {
  int vcnt = vertices.size();

  if (a >= vcnt || b >= vcnt || c >= vcnt)
    return false;

  TrimeshFace *newFace = new TrimeshFace(this, a, b, c);
  if (!newFace->degen)
    faces.push_back(newFace);
  else
    delete newFace;

  // Don't add faces to the scene's object list so we can cull by bounding
  // box
  return true;
}

// Check to make sure that if we have per-vertex materials or normals
// they are the right number.
const char *Trimesh::doubleCheck() {
  if (!vertColors.empty() && vertColors.size() != vertices.size())
    return "Bad Trimesh: Wrong number of vertex colors.";
  if (!uvCoords.empty() && uvCoords.size() != vertices.size())
    return "Bad Trimesh: Wrong number of UV coordinates.";
  if (!normals.empty() && normals.size() != vertices.size())
    return "Bad Trimesh: Wrong number of normals.";

  bvh.build(faces);
  
  return 0;
}

bool Trimesh::intersectLocal(ray &r, isect &i) const {
  // bool have_one = false;
  // for (auto face : faces) {
  //   isect cur;
  //   if (face->intersectLocal(r, cur)) {
  //     if (!have_one || (cur.getT() < i.getT())) {
  //       i = cur;
  //       have_one = true;
  //     }
  //   }
  // }
  // if (!have_one)
  //   i.setT(1000.0);
  // return have_one;
   return bvh.intersect(r, i);
}

bool TrimeshFace::intersect(ray &r, isect &i) const {
  return intersectLocal(r, i);
}


// Intersect ray r with the triangle abc.  If it hits returns true,
// and put the parameter in t and the barycentric coordinates of the
// intersection in u (alpha) and v (beta).
bool TrimeshFace::intersectLocal(ray &r, isect &i) const {
  const glm::dvec3 &v0 = parent->vertices[ids[0]];
  const glm::dvec3 &v1 = parent->vertices[ids[1]];
  const glm::dvec3 &v2 = parent->vertices[ids[2]];

  glm::dvec3 edge1 = v1 - v0;
  glm::dvec3 edge2 = v2 - v0;

  glm::dvec3 pvec = glm::cross(r.getDirection(), edge2);
  double det = glm::dot(edge1, pvec);

  if (std::abs(det) < 1e-8) return false;

  double invDet = 1.0 / det;

  glm::dvec3 tvec = r.getPosition() - v0;
  double u = glm::dot(tvec, pvec) * invDet;

  if (u < 0.0 || u > 1.0) return false;

  glm::dvec3 qvec = glm::cross(tvec, edge1);
  double v = glm::dot(r.getDirection(), qvec) * invDet;

  if (v < 0.0 || u + v > 1.0) return false;

  double t = glm::dot(edge2, qvec) * invDet;

  if (t < 1e-7) return false;

  i.setObject(this->parent);
  i.setT(t);
  
  double w = 1.0 - u - v;
  i.setBary(u, v, w);

  if (parent->vertNorms) {
      const glm::dvec3 &n0 = parent->normals[ids[0]];
      const glm::dvec3 &n1 = parent->normals[ids[1]];
      const glm::dvec3 &n2 = parent->normals[ids[2]];
      i.setN(glm::normalize((w * n0) + (u * n1) + (v * n2)));
  } else {
      i.setN(this->normal);
  }

  if (!parent->uvCoords.empty()) {
      const glm::dvec2 &uv0 = parent->uvCoords[ids[0]];
      const glm::dvec2 &uv1 = parent->uvCoords[ids[1]];
      const glm::dvec2 &uv2 = parent->uvCoords[ids[2]];
      i.setUVCoordinates((w * uv0) + (u * uv1) + (v * uv2));
      
      i.setMaterial(parent->getMaterial());
  } 
  else if (!parent->vertColors.empty()) {
      const glm::dvec3 &c0 = parent->vertColors[ids[0]];
      const glm::dvec3 &c1 = parent->vertColors[ids[1]];
      const glm::dvec3 &c2 = parent->vertColors[ids[2]];
      glm::dvec3 interpColor = (w * c0) + (u * c1) + (v * c2);
      
      Material m = parent->getMaterial();
      m.setDiffuse(interpColor);
      i.setMaterial(m);
  } 
  else {
      i.setMaterial(parent->getMaterial());
  }

  return true;
}

// Once all the verts and faces are loaded, per vertex normals can be
// generated by averaging the normals of the neighboring faces.
void Trimesh::generateNormals() {
  int cnt = vertices.size();
  normals.resize(cnt);
  std::vector<int> numFaces(cnt, 0);

  for (auto face : faces) {
    glm::dvec3 faceNormal = face->getNormal();

    for (int i = 0; i < 3; ++i) {
      normals[(*face)[i]] += faceNormal;
      ++numFaces[(*face)[i]];
    }
  }

  for (int i = 0; i < cnt; ++i) {
    if (numFaces[i])
      normals[i] /= numFaces[i];
  }

  vertNorms = true;
}

